#!/bin/bash
set -e

 : ${target_name:=dist}
 : ${work_path:=.}
 : ${app:=$(basename $(cd "${work_path}"; pwd))}
 : ${osarchi:="$(go env GOHOSTOS)-$(go env GOHOSTARCH)"}
 : ${release_osarchi:="linux-amd64,darwin-amd64,windows-amd64"}
 : ${version:="$[$(git -C . describe --abbrev=0 --tags HEAD | tr -d 'v') + 1]-dev"}
 : ${upx:="$(command -v upx 2>/dev/null)"}
 : ${build_packages:=}
 : ${build_ldflags:="-s -w -X main.BuildTime=`date -u '+%Y-%m-%d_%H:%M:%S_UTC'` -X main.BuildVersion=\${version} -X main.BuildCommit=`git rev-parse --short HEAD`"}
 : ${errcheck:=1}

read -d '' helper <<EOF || true
Usage: gomake [-v version] command...
  gomake is a script to build go apps

  command
      clean                 clean '${target_name}/' directory
      build                 build (current platform only by default)
      quality               Format, Fix, check error handled, lint, vet, misspell, ineffassign, Gocyclo
      test                  run go tests
      install               install release to \$GOPATH/bin
      gomake_update         self updating by downloading and replacing with latest version

         default is 'clean build test quality'

  -v, --version=version     version of the app
  -h, --help                this helper
  -W, --work-path=path      set working path, default is ./
EOF

go_files=$(find . -type f -name '*.go' -not -path "./_*" -not -path "./vendor/*")
err_count=0

#color_red() {
#    echo -n -e "\e[0;31m"
#}
#
#color_reset() {
#    echo -n -e "\e[0m"
#}

echo_red() {
    echo -n -e "\e[0;31m"
    echo "${@}"
    echo -n -e "\e[0m"
}

echo_purple() {
    echo -e "\e[0;35m${@}\e[0m"
}

echo_green() {
    echo -e "\e[0;32m${@}\e[0m"
}

echo_yellow() {
    echo -e "\e[0;93m${@}\e[0m"
}

err_count() {
    c=$(echo -e "${1}" | wc -l)
    ((err_count+=${c}))
}

gomake_update() {
    echo_green "Downloading gomake"
    wget -q -O ${work_path}/gomake.tmp https://raw.githubusercontent.com/n0rad/gomake/master/gomake
    chmod +x ${work_path}/gomake.tmp
    mv ${work_path}/gomake.tmp ${work_path}/$0
}

clean() {
    echo_green "Cleaning"
    rm -Rf ${work_path}/${target_name}
}

build() {
    start=`date +%s`

    [ -z "$1" ] || osarchi="$1"
    [ ! -z ${version+x} ] || version="0"

    mkdir -p ${work_path}/${target_name}/bindata

    if [ `type -t pre-build`"" == 'function' ]; then
        pre-build
    fi

    echo_green "Goimports"
    [ -f ${GOPATH}/bin/goimports ] || go get -u golang.org/x/tools/cmd/goimports
    goimports -w ${go_files}

    echo_green "Format"
    gofmt -w -s ${go_files}

    echo_green "Fix"
    go tool fix ${go_files}

    if [ "$(ls -A ${work_path}/${target_name}/bindata)" ]; then
        [ -f ${GOPATH}/bin/go-bindata ] || go get -u github.com/jteeuwen/go-bindata/...
        go-bindata -nomemcopy -pkg dist -prefix dist/bindata -o ${work_path}/${target_name}/bindata.go ${work_path}/${target_name}/bindata/...
    fi

    ldflags=$(eval echo ${build_ldflags})
    IFS=',' read -ra current <<< "$osarchi"
    for e in "${current[@]}"; do
        echo_green "Building $e"

        binaryPath=$(targetBinaryPath ${e})
        $(cd ${work_path} && GOOS="${e%-*}" GOARCH="${e#*-}" go build -ldflags "${ldflags}" -o ${target_name}/${binaryPath} ${build_packages})

        if [[ "${upx}" ]]; then
            echo_green "Compressing ${e}"
            "${upx}" ${work_path}/${target_name}/${binaryPath} &>/dev/null
        fi

        if [ "${e%-*}" == "windows" ]; then
            mv ${work_path}/${target_name}/${binaryPath} ${work_path}/${target_name}/${binaryPath}.exe
        fi
    done
    echo_purple "Build duration : $((`date +%s`-${start}))s"
}

targetBinaryPath() {
    echo ${app}-v${version}-${1}/${app}
}

install() {
    echo_green "Installing"
    cp ${work_path}/${target_name}/${app}-v${version}-$(go env GOHOSTOS)-$(go env GOHOSTARCH)/${app}* ${GOPATH}/bin/
}

quality() {
    start=`date +%s`
    cd ${work_path}

    if [ ${errcheck} == 1 ]; then
        echo_green "Err check"
        [ -f ${GOPATH}/bin/errcheck ] || go get -u github.com/kisielk/errcheck
        res=$(errcheck ./... | grep -v 'vendor/' | grep -v 'Close(' | grep -v '_test.go')
        err_count "${res}"
        echo_red "${res}"
    fi

    echo_green "Lint"
    [ -f ${GOPATH}/bin/golint ] || go get -u github.com/golang/lint/golint
    for i in ${go_files}; do
        golint ${i} | grep -v 'should have comment ' || true
    done

    echo_green "Vet"
    go tool vet ${go_files} || true

    echo_green "Misspell"
    [ -f ${GOPATH}/bin/misspell ] || go get -u github.com/client9/misspell/cmd/misspell
    misspell -source=text ${go_files}

    echo_green "Ineffassign"
    [ -f ${GOPATH}/bin/ineffassign ] || go get -u github.com/gordonklaus/ineffassign
    for i in ${go_files}; do
        ineffassign -n ${i} || true
    done

    echo_green "Gocyclo"
    [ -f ${GOPATH}/bin/gocyclo ] || go get -u github.com/fzipp/gocyclo
    gocyclo -over 15 ${go_files} || true

    cd -
    echo_purple "Quality duration : $((`date +%s`-${start}))s"
}

require_clean_work_tree() {
    # Update the index
    git update-index -q --ignore-submodules --refresh
    err=0

    # Disallow unstaged changes in the working tree
    if ! git diff-files --quiet --ignore-submodules --
    then
        echo_red "cannot release: you have unstaged changes."
        git diff-files --name-status -r --ignore-submodules -- >&2
        err=1
    fi

    # Disallow uncommitted changes in the index
    if ! git diff-index --cached --quiet HEAD --ignore-submodules --
    then
        echo_red "cannot release: your index contains uncommitted changes."
        git diff-index --cached --name-status -r --ignore-submodules HEAD -- >&2
        err=1
    fi

    if [ ${err} = 1 ]
    then
        echo_red "Please commit or stash them."
        exit 1
    fi
}

test() {
    start=`date +%s`
    echo_green "Testing"
    go test -cover $(go list ${work_path}/... | grep -v vendor/)

    if [ `type -t extra-test`"" == 'function' ]; then
        extra-test
    fi

    echo_purple "Test duration : $((`date +%s`-${start}))s"
}

#########################################
#########################################

global_start=`date +%s`

commands=()
while [ $# -gt 0 ]; do
    case "${1}" in
        -h|--help)  echo "${helper}"; exit 0;;
        --version=*)version="${1#*=}"; shift;;
        --work-path=*) work_path="${1#*=}"; shift;;
        -v)         version="${2}"; [ $# -gt 1 ] || (echo_red "Missing argument for ${1}"; exit 1); shift 2;;
        -W)         work_path="${2}"; [ $# -gt 1 ] || (echo_red "Missing argument for ${1}"; exit 1); shift 2;;
        --)         shift; commands+=("${@}"); break;;
        *)          commands+=("${1}"); shift;;
    esac
done

if [ -f ${work_path}/gomake.cfg ]; then
 . ${work_path}/gomake.cfg
fi

if [ ${#commands[@]} -eq 0 ]; then
    commands=(clean build test quality)
fi
command_count=0
for i in "${commands[@]}"; do
    case ${i} in
        test|build|clean|quality|install|gomake_update) ${i}; ((++command_count));;
        *)                                              echo_red "Unknown command '${i}'"; echo ${helper}; exit 1;;
    esac
done

if [ ${command_count} -gt 1 ]; then
    echo_purple "Global duration : $((`date +%s`-global_start))s"
fi

exit 0
